### ISSUE TITLE
Docker container doesn't run after a fresh build

### ISSUE THREAD

**Issue by bschonec** [naveenrajm7/rpmbuild#24]
As shown below, the Docker container crashes immediately upon entry when running...

```

docker build -t <image name> .

<snip snip>

example@example.com:~/rpmbuild-action$ podman run --rm --name test_container -it a6542a708894
/node_modules/undici/lib/handler/RetryHandler.js:29
    } = retryOptions ?? {}
                      ^

SyntaxError: Unexpected token '?'
    at wrapSafe (internal/modules/cjs/loader.js:1072:16)
    at Module._compile (internal/modules/cjs/loader.js:1122:27)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1178:10)
    at Module.load (internal/modules/cjs/loader.js:1002:32)
    at Function.Module._load (internal/modules/cjs/loader.js:901:14)
    at Module.require (internal/modules/cjs/loader.js:1044:19)
    at require (internal/modules/cjs/helpers.js:77:18)
    at Object.<anonymous> (/node_modules/undici/index.js:18:22)
    at Module._compile (internal/modules/cjs/loader.js:1158:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1178:10)
```

#23 fixes this problem.

**Comment by bschonec** [comment]
Is the project dead?

**Comment by naveenrajm7** [comment]
Hi 

Sorry for the delayed response. This project was created as a response to the [GitHub Actions Inaugural hackathon](https://githubhackathon.com/#hackathon), and was never really worked on after the hackathon period.
Given the simplicity of the project, I found people forked the work and customized it according to their need, which is evident by this repo having more forks than stars.

Having said that if there is value in resuming the work on this project, I am happy to do that. However, I will need some time to learn the current state of building GitHub Actions and also relearn what I have built. 

Regarding this issue, if the PR you mentioned fixes the problem, I can merge it. But it takes time for me to evaluate the fix. 
I will get back to this, once I complete some tasks in my other open source project. 

If you have tested PR #23 , let me know. So I can merge it.

Thanks.

**Comment by bschonec** [comment]
@naveenrajm7 #23 does fix my issue.

**Comment by bschonec** [comment]
@naveenrajm7 checking in.

**Comment by naveenrajm7** [comment]
Doesn't the PR that you linked solve your issue ?
I merged it since you said it would solve.
